// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/lang/cached_document.proto

package lang

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CachedDocument struct {
	Cache                string    `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	Value                *Document `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CachedDocument) Reset()         { *m = CachedDocument{} }
func (m *CachedDocument) String() string { return proto.CompactTextString(m) }
func (*CachedDocument) ProtoMessage()    {}
func (*CachedDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1bc25c9cada41f1, []int{0}
}
func (m *CachedDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CachedDocument.Unmarshal(m, b)
}
func (m *CachedDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CachedDocument.Marshal(b, m, deterministic)
}
func (m *CachedDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachedDocument.Merge(m, src)
}
func (m *CachedDocument) XXX_Size() int {
	return xxx_messageInfo_CachedDocument.Size(m)
}
func (m *CachedDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_CachedDocument.DiscardUnknown(m)
}

var xxx_messageInfo_CachedDocument proto.InternalMessageInfo

func (m *CachedDocument) GetCache() string {
	if m != nil {
		return m.Cache
	}
	return ""
}

func (m *CachedDocument) GetValue() *Document {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*CachedDocument)(nil), "mojo.lang.CachedDocument")
}

func init() { proto.RegisterFile("mojo/lang/cached_document.proto", fileDescriptor_f1bc25c9cada41f1) }

var fileDescriptor_f1bc25c9cada41f1 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x49, 0xcc, 0x4b, 0xd7, 0x4f, 0x4e, 0x4c, 0xce, 0x48, 0x4d, 0x89, 0x4f, 0xc9, 0x4f,
	0x2e, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x29, 0xd0,
	0x03, 0x29, 0x90, 0x92, 0x40, 0xa8, 0x45, 0x55, 0xa4, 0x14, 0xc8, 0xc5, 0xe7, 0x0c, 0xd6, 0xed,
	0x02, 0x15, 0x17, 0x12, 0xe1, 0x62, 0x05, 0x9b, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0xe1, 0x08, 0x69, 0x72, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70,
	0x1b, 0x09, 0xeb, 0xc1, 0x0d, 0xd7, 0x83, 0xe9, 0x0c, 0x82, 0xa8, 0x70, 0x32, 0x8c, 0xd2, 0x4f,
	0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x07, 0xa9, 0xd3, 0x05, 0xdb, 0x0c,
	0x26, 0xd2, 0xf3, 0xf5, 0x0b, 0xb2, 0xd3, 0xf5, 0xe1, 0xee, 0xb1, 0x06, 0x11, 0x49, 0x6c, 0x60,
	0xc7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0xc0, 0xde, 0xfe, 0xd4, 0x00, 0x00, 0x00,
}
