// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/lang/document.proto

package lang

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	StartPosition        *Position       `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition          *Position       `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	Lines                []*LineDocument `protobuf:"bytes,15,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a6b46431335f62, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *Document) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *Document) GetLines() []*LineDocument {
	if m != nil {
		return m.Lines
	}
	return nil
}

type LineDocument struct {
	StartPosition        *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition          *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	Line                 string    `protobuf:"bytes,15,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LineDocument) Reset()         { *m = LineDocument{} }
func (m *LineDocument) String() string { return proto.CompactTextString(m) }
func (*LineDocument) ProtoMessage()    {}
func (*LineDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a6b46431335f62, []int{1}
}
func (m *LineDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineDocument.Unmarshal(m, b)
}
func (m *LineDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineDocument.Marshal(b, m, deterministic)
}
func (m *LineDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineDocument.Merge(m, src)
}
func (m *LineDocument) XXX_Size() int {
	return xxx_messageInfo_LineDocument.Size(m)
}
func (m *LineDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_LineDocument.DiscardUnknown(m)
}

var xxx_messageInfo_LineDocument proto.InternalMessageInfo

func (m *LineDocument) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *LineDocument) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *LineDocument) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "mojo.lang.Document")
	proto.RegisterType((*LineDocument)(nil), "mojo.lang.LineDocument")
}

func init() { proto.RegisterFile("mojo/lang/document.proto", fileDescriptor_d4a6b46431335f62) }

var fileDescriptor_d4a6b46431335f62 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0xcd, 0xcf, 0xca,
	0xd7, 0xcf, 0x49, 0xcc, 0x4b, 0xd7, 0x4f, 0xc9, 0x4f, 0x2e, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xc9, 0xe8, 0x81, 0x64, 0xa4, 0x90, 0x14, 0x15, 0xe4,
	0x17, 0x67, 0x96, 0x64, 0xe6, 0xe7, 0x41, 0x14, 0x29, 0xad, 0x65, 0xe4, 0xe2, 0x70, 0x81, 0xea,
	0x13, 0xb2, 0xe2, 0xe2, 0x2b, 0x2e, 0x49, 0x2c, 0x2a, 0x89, 0x87, 0x29, 0x92, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x36, 0x12, 0xd6, 0x83, 0x1b, 0xa5, 0x17, 0x00, 0x95, 0x0a, 0xe2, 0x05, 0x2b, 0x85,
	0x71, 0x85, 0xcc, 0xb8, 0x78, 0x52, 0xf3, 0x52, 0x10, 0x3a, 0x99, 0x70, 0xeb, 0xe4, 0x4e, 0xcd,
	0x4b, 0x81, 0xeb, 0xd3, 0xe5, 0x62, 0xcd, 0xc9, 0xcc, 0x4b, 0x2d, 0x96, 0xe0, 0x57, 0x60, 0xd6,
	0xe0, 0x36, 0x12, 0x47, 0xd2, 0xe0, 0x93, 0x99, 0x97, 0x0a, 0x73, 0x5b, 0x10, 0x44, 0x95, 0xd2,
	0x34, 0x46, 0x2e, 0x1e, 0x64, 0xf1, 0x01, 0x71, 0xb3, 0x10, 0x17, 0x0b, 0xc8, 0x35, 0x12, 0xfc,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x93, 0x61, 0x94, 0x7e, 0x7a, 0x66, 0x49, 0x46, 0x69,
	0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0xc8, 0x04, 0x5d, 0x70, 0x78, 0x83, 0x89, 0xf4, 0x7c, 0xfd,
	0x82, 0xec, 0x74, 0x7d, 0x78, 0x2c, 0x58, 0x83, 0x88, 0x24, 0x36, 0x70, 0x14, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0xe2, 0xe7, 0x1a, 0xc3, 0x01, 0x00, 0x00,
}
