// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/branch_stmt.proto

package org.mojolang.mojo.lang;

public final class BranchStmtProto {
  private BranchStmtProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_lang_BranchStmt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_lang_BranchStmt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mojo/lang/branch_stmt.proto\022\tmojo.lang" +
      "\032\030mojo/lang/position.proto\032\024mojo/lang/st" +
      "mt.proto\"\204\001\n\nBranchStmt\022+\n\016start_positio" +
      "n\030\001 \001(\0132\023.mojo.lang.Position\022)\n\014end_posi" +
      "tion\030\002 \001(\0132\023.mojo.lang.Position\022\014\n\004kind\030" +
      "\003 \001(\003\022\020\n\010implicit\030\004 \001(\010B\\\n\026org.mojolang." +
      "mojo.langB\017BranchStmtProtoP\001Z/github.com" +
      "/mojo-lang/lang/go/pkg/mojo/lang;langb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.lang.PositionProto.getDescriptor(),
          org.mojolang.mojo.lang.StmtProto.getDescriptor(),
        });
    internal_static_mojo_lang_BranchStmt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_lang_BranchStmt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_lang_BranchStmt_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", });
    org.mojolang.mojo.lang.PositionProto.getDescriptor();
    org.mojolang.mojo.lang.StmtProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
