// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/lang.proto

package org.mojolang.mojo.lang;

/**
 * Protobuf type {@code mojo.lang.ImportDecl}
 */
public final class ImportDecl extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.lang.ImportDecl)
    ImportDeclOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImportDecl.newBuilder() to construct.
  private ImportDecl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImportDecl() {
    packageName_ = "";
    sourceFileName_ = "";
    filter_ = "";
    attributes_ = java.util.Collections.emptyList();
    importPackageName_ = "";
    importPackageAlias_ = "";
    importFileName_ = "";
    identifiers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImportDecl();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImportDecl(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (startPosition_ != null) {
              subBuilder = startPosition_.toBuilder();
            }
            startPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startPosition_);
              startPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (endPosition_ != null) {
              subBuilder = endPosition_.toBuilder();
            }
            endPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endPosition_);
              endPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            implicit_ = input.readBool();
            break;
          }
          case 50: {
            org.mojolang.mojo.lang.Document.Builder subBuilder = null;
            if (document_ != null) {
              subBuilder = document_.toBuilder();
            }
            document_ = input.readMessage(org.mojolang.mojo.lang.Document.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(document_);
              document_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            sourceFileName_ = s;
            break;
          }
          case 74: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (keywordPosition_ != null) {
              subBuilder = keywordPosition_.toBuilder();
            }
            keywordPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(keywordPosition_);
              keywordPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            filter_ = s;
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              attributes_ = new java.util.ArrayList<org.mojolang.mojo.lang.Attribute>();
              mutable_bitField0_ |= 0x00000001;
            }
            attributes_.add(
                input.readMessage(org.mojolang.mojo.lang.Attribute.parser(), extensionRegistry));
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            importPackageName_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            importPackageAlias_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            importFileName_ = s;
            break;
          }
          case 130: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              identifiers_ = new java.util.ArrayList<org.mojolang.mojo.lang.Identifier>();
              mutable_bitField0_ |= 0x00000002;
            }
            identifiers_.add(
                input.readMessage(org.mojolang.mojo.lang.Identifier.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        attributes_ = java.util.Collections.unmodifiableList(attributes_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        identifiers_ = java.util.Collections.unmodifiableList(identifiers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.lang.LangProto.internal_static_mojo_lang_ImportDecl_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.lang.LangProto.internal_static_mojo_lang_ImportDecl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.lang.ImportDecl.class, org.mojolang.mojo.lang.ImportDecl.Builder.class);
  }

  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  @java.lang.Override
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return getStartPosition();
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  @java.lang.Override
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return getEndPosition();
  }

  public static final int IMPLICIT_FIELD_NUMBER = 5;
  private boolean implicit_;
  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public boolean getImplicit() {
    return implicit_;
  }

  public static final int DOCUMENT_FIELD_NUMBER = 6;
  private org.mojolang.mojo.lang.Document document_;
  /**
   * <code>.mojo.lang.Document document = 6;</code>
   * @return Whether the document field is set.
   */
  @java.lang.Override
  public boolean hasDocument() {
    return document_ != null;
  }
  /**
   * <code>.mojo.lang.Document document = 6;</code>
   * @return The document.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Document getDocument() {
    return document_ == null ? org.mojolang.mojo.lang.Document.getDefaultInstance() : document_;
  }
  /**
   * <code>.mojo.lang.Document document = 6;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.DocumentOrBuilder getDocumentOrBuilder() {
    return getDocument();
  }

  public static final int PACKAGE_NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object packageName_;
  /**
   * <code>string package_name = 7;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <code>string package_name = 7;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FILE_NAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object sourceFileName_;
  /**
   * <code>string source_file_name = 8;</code>
   * @return The sourceFileName.
   */
  @java.lang.Override
  public java.lang.String getSourceFileName() {
    java.lang.Object ref = sourceFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string source_file_name = 8;</code>
   * @return The bytes for sourceFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceFileNameBytes() {
    java.lang.Object ref = sourceFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORD_POSITION_FIELD_NUMBER = 9;
  private org.mojolang.mojo.lang.Position keywordPosition_;
  /**
   * <code>.mojo.lang.Position keyword_position = 9;</code>
   * @return Whether the keywordPosition field is set.
   */
  @java.lang.Override
  public boolean hasKeywordPosition() {
    return keywordPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position keyword_position = 9;</code>
   * @return The keywordPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getKeywordPosition() {
    return keywordPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : keywordPosition_;
  }
  /**
   * <code>.mojo.lang.Position keyword_position = 9;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getKeywordPositionOrBuilder() {
    return getKeywordPosition();
  }

  public static final int FILTER_FIELD_NUMBER = 11;
  private volatile java.lang.Object filter_;
  /**
   * <code>string filter = 11;</code>
   * @return The filter.
   */
  @java.lang.Override
  public java.lang.String getFilter() {
    java.lang.Object ref = filter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filter_ = s;
      return s;
    }
  }
  /**
   * <code>string filter = 11;</code>
   * @return The bytes for filter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterBytes() {
    java.lang.Object ref = filter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 12;
  private java.util.List<org.mojolang.mojo.lang.Attribute> attributes_;
  /**
   * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.lang.Attribute> getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.lang.AttributeOrBuilder> 
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
   */
  @java.lang.Override
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Attribute getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.AttributeOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }

  public static final int IMPORT_PACKAGE_NAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object importPackageName_;
  /**
   * <code>string import_package_name = 13;</code>
   * @return The importPackageName.
   */
  @java.lang.Override
  public java.lang.String getImportPackageName() {
    java.lang.Object ref = importPackageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      importPackageName_ = s;
      return s;
    }
  }
  /**
   * <code>string import_package_name = 13;</code>
   * @return The bytes for importPackageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImportPackageNameBytes() {
    java.lang.Object ref = importPackageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      importPackageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMPORT_PACKAGE_ALIAS_FIELD_NUMBER = 14;
  private volatile java.lang.Object importPackageAlias_;
  /**
   * <code>string import_package_alias = 14;</code>
   * @return The importPackageAlias.
   */
  @java.lang.Override
  public java.lang.String getImportPackageAlias() {
    java.lang.Object ref = importPackageAlias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      importPackageAlias_ = s;
      return s;
    }
  }
  /**
   * <code>string import_package_alias = 14;</code>
   * @return The bytes for importPackageAlias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImportPackageAliasBytes() {
    java.lang.Object ref = importPackageAlias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      importPackageAlias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMPORT_FILE_NAME_FIELD_NUMBER = 15;
  private volatile java.lang.Object importFileName_;
  /**
   * <code>string import_file_name = 15;</code>
   * @return The importFileName.
   */
  @java.lang.Override
  public java.lang.String getImportFileName() {
    java.lang.Object ref = importFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      importFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string import_file_name = 15;</code>
   * @return The bytes for importFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImportFileNameBytes() {
    java.lang.Object ref = importFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      importFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTIFIERS_FIELD_NUMBER = 16;
  private java.util.List<org.mojolang.mojo.lang.Identifier> identifiers_;
  /**
   * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.lang.Identifier> getIdentifiersList() {
    return identifiers_;
  }
  /**
   * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.lang.IdentifierOrBuilder> 
      getIdentifiersOrBuilderList() {
    return identifiers_;
  }
  /**
   * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
   */
  @java.lang.Override
  public int getIdentifiersCount() {
    return identifiers_.size();
  }
  /**
   * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Identifier getIdentifiers(int index) {
    return identifiers_.get(index);
  }
  /**
   * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.IdentifierOrBuilder getIdentifiersOrBuilder(
      int index) {
    return identifiers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (implicit_ != false) {
      output.writeBool(5, implicit_);
    }
    if (document_ != null) {
      output.writeMessage(6, getDocument());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, packageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceFileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sourceFileName_);
    }
    if (keywordPosition_ != null) {
      output.writeMessage(9, getKeywordPosition());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filter_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, filter_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      output.writeMessage(12, attributes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPackageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, importPackageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPackageAlias_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, importPackageAlias_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importFileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, importFileName_);
    }
    for (int i = 0; i < identifiers_.size(); i++) {
      output.writeMessage(16, identifiers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (implicit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, implicit_);
    }
    if (document_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDocument());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, packageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceFileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sourceFileName_);
    }
    if (keywordPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getKeywordPosition());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filter_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, filter_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, attributes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPackageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, importPackageName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importPackageAlias_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, importPackageAlias_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(importFileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, importFileName_);
    }
    for (int i = 0; i < identifiers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, identifiers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.lang.ImportDecl)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.lang.ImportDecl other = (org.mojolang.mojo.lang.ImportDecl) obj;

    if (hasStartPosition() != other.hasStartPosition()) return false;
    if (hasStartPosition()) {
      if (!getStartPosition()
          .equals(other.getStartPosition())) return false;
    }
    if (hasEndPosition() != other.hasEndPosition()) return false;
    if (hasEndPosition()) {
      if (!getEndPosition()
          .equals(other.getEndPosition())) return false;
    }
    if (getImplicit()
        != other.getImplicit()) return false;
    if (hasDocument() != other.hasDocument()) return false;
    if (hasDocument()) {
      if (!getDocument()
          .equals(other.getDocument())) return false;
    }
    if (!getPackageName()
        .equals(other.getPackageName())) return false;
    if (!getSourceFileName()
        .equals(other.getSourceFileName())) return false;
    if (hasKeywordPosition() != other.hasKeywordPosition()) return false;
    if (hasKeywordPosition()) {
      if (!getKeywordPosition()
          .equals(other.getKeywordPosition())) return false;
    }
    if (!getFilter()
        .equals(other.getFilter())) return false;
    if (!getAttributesList()
        .equals(other.getAttributesList())) return false;
    if (!getImportPackageName()
        .equals(other.getImportPackageName())) return false;
    if (!getImportPackageAlias()
        .equals(other.getImportPackageAlias())) return false;
    if (!getImportFileName()
        .equals(other.getImportFileName())) return false;
    if (!getIdentifiersList()
        .equals(other.getIdentifiersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImplicit());
    if (hasDocument()) {
      hash = (37 * hash) + DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDocument().hashCode();
    }
    hash = (37 * hash) + PACKAGE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    hash = (37 * hash) + SOURCE_FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSourceFileName().hashCode();
    if (hasKeywordPosition()) {
      hash = (37 * hash) + KEYWORD_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordPosition().hashCode();
    }
    hash = (37 * hash) + FILTER_FIELD_NUMBER;
    hash = (53 * hash) + getFilter().hashCode();
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    hash = (37 * hash) + IMPORT_PACKAGE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getImportPackageName().hashCode();
    hash = (37 * hash) + IMPORT_PACKAGE_ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getImportPackageAlias().hashCode();
    hash = (37 * hash) + IMPORT_FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getImportFileName().hashCode();
    if (getIdentifiersCount() > 0) {
      hash = (37 * hash) + IDENTIFIERS_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifiersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.ImportDecl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.lang.ImportDecl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.lang.ImportDecl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.lang.ImportDecl)
      org.mojolang.mojo.lang.ImportDeclOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.lang.LangProto.internal_static_mojo_lang_ImportDecl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.lang.LangProto.internal_static_mojo_lang_ImportDecl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.lang.ImportDecl.class, org.mojolang.mojo.lang.ImportDecl.Builder.class);
    }

    // Construct using org.mojolang.mojo.lang.ImportDecl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttributesFieldBuilder();
        getIdentifiersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }
      implicit_ = false;

      if (documentBuilder_ == null) {
        document_ = null;
      } else {
        document_ = null;
        documentBuilder_ = null;
      }
      packageName_ = "";

      sourceFileName_ = "";

      if (keywordPositionBuilder_ == null) {
        keywordPosition_ = null;
      } else {
        keywordPosition_ = null;
        keywordPositionBuilder_ = null;
      }
      filter_ = "";

      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        attributesBuilder_.clear();
      }
      importPackageName_ = "";

      importPackageAlias_ = "";

      importFileName_ = "";

      if (identifiersBuilder_ == null) {
        identifiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        identifiersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.lang.LangProto.internal_static_mojo_lang_ImportDecl_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.ImportDecl getDefaultInstanceForType() {
      return org.mojolang.mojo.lang.ImportDecl.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.ImportDecl build() {
      org.mojolang.mojo.lang.ImportDecl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.ImportDecl buildPartial() {
      org.mojolang.mojo.lang.ImportDecl result = new org.mojolang.mojo.lang.ImportDecl(this);
      int from_bitField0_ = bitField0_;
      if (startPositionBuilder_ == null) {
        result.startPosition_ = startPosition_;
      } else {
        result.startPosition_ = startPositionBuilder_.build();
      }
      if (endPositionBuilder_ == null) {
        result.endPosition_ = endPosition_;
      } else {
        result.endPosition_ = endPositionBuilder_.build();
      }
      result.implicit_ = implicit_;
      if (documentBuilder_ == null) {
        result.document_ = document_;
      } else {
        result.document_ = documentBuilder_.build();
      }
      result.packageName_ = packageName_;
      result.sourceFileName_ = sourceFileName_;
      if (keywordPositionBuilder_ == null) {
        result.keywordPosition_ = keywordPosition_;
      } else {
        result.keywordPosition_ = keywordPositionBuilder_.build();
      }
      result.filter_ = filter_;
      if (attributesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attributes_ = attributes_;
      } else {
        result.attributes_ = attributesBuilder_.build();
      }
      result.importPackageName_ = importPackageName_;
      result.importPackageAlias_ = importPackageAlias_;
      result.importFileName_ = importFileName_;
      if (identifiersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          identifiers_ = java.util.Collections.unmodifiableList(identifiers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.identifiers_ = identifiers_;
      } else {
        result.identifiers_ = identifiersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.lang.ImportDecl) {
        return mergeFrom((org.mojolang.mojo.lang.ImportDecl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.lang.ImportDecl other) {
      if (other == org.mojolang.mojo.lang.ImportDecl.getDefaultInstance()) return this;
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (other.getImplicit() != false) {
        setImplicit(other.getImplicit());
      }
      if (other.hasDocument()) {
        mergeDocument(other.getDocument());
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      if (!other.getSourceFileName().isEmpty()) {
        sourceFileName_ = other.sourceFileName_;
        onChanged();
      }
      if (other.hasKeywordPosition()) {
        mergeKeywordPosition(other.getKeywordPosition());
      }
      if (!other.getFilter().isEmpty()) {
        filter_ = other.filter_;
        onChanged();
      }
      if (attributesBuilder_ == null) {
        if (!other.attributes_.isEmpty()) {
          if (attributes_.isEmpty()) {
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttributesIsMutable();
            attributes_.addAll(other.attributes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributes_.isEmpty()) {
          if (attributesBuilder_.isEmpty()) {
            attributesBuilder_.dispose();
            attributesBuilder_ = null;
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            attributesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributesFieldBuilder() : null;
          } else {
            attributesBuilder_.addAllMessages(other.attributes_);
          }
        }
      }
      if (!other.getImportPackageName().isEmpty()) {
        importPackageName_ = other.importPackageName_;
        onChanged();
      }
      if (!other.getImportPackageAlias().isEmpty()) {
        importPackageAlias_ = other.importPackageAlias_;
        onChanged();
      }
      if (!other.getImportFileName().isEmpty()) {
        importFileName_ = other.importFileName_;
        onChanged();
      }
      if (identifiersBuilder_ == null) {
        if (!other.identifiers_.isEmpty()) {
          if (identifiers_.isEmpty()) {
            identifiers_ = other.identifiers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIdentifiersIsMutable();
            identifiers_.addAll(other.identifiers_);
          }
          onChanged();
        }
      } else {
        if (!other.identifiers_.isEmpty()) {
          if (identifiersBuilder_.isEmpty()) {
            identifiersBuilder_.dispose();
            identifiersBuilder_ = null;
            identifiers_ = other.identifiers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            identifiersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIdentifiersFieldBuilder() : null;
          } else {
            identifiersBuilder_.addAllMessages(other.identifiers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.lang.ImportDecl parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.lang.ImportDecl) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.lang.Position startPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return Whether the startPosition field is set.
     */
    public boolean hasStartPosition() {
      return startPositionBuilder_ != null || startPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return The startPosition.
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
        onChanged();
      } else {
        startPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
        onChanged();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (startPosition_ != null) {
          startPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(startPosition_).mergeFrom(value).buildPartial();
        } else {
          startPosition_ = value;
        }
        onChanged();
      } else {
        startPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
        onChanged();
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return Whether the endPosition field is set.
     */
    public boolean hasEndPosition() {
      return endPositionBuilder_ != null || endPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return The endPosition.
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
        onChanged();
      } else {
        endPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
        onChanged();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (endPosition_ != null) {
          endPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
        } else {
          endPosition_ = value;
        }
        onChanged();
      } else {
        endPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
        onChanged();
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private boolean implicit_ ;
    /**
     * <code>bool implicit = 5;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public boolean getImplicit() {
      return implicit_;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @param value The implicit to set.
     * @return This builder for chaining.
     */
    public Builder setImplicit(boolean value) {
      
      implicit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplicit() {
      
      implicit_ = false;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.lang.Document document_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Document, org.mojolang.mojo.lang.Document.Builder, org.mojolang.mojo.lang.DocumentOrBuilder> documentBuilder_;
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     * @return Whether the document field is set.
     */
    public boolean hasDocument() {
      return documentBuilder_ != null || document_ != null;
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     * @return The document.
     */
    public org.mojolang.mojo.lang.Document getDocument() {
      if (documentBuilder_ == null) {
        return document_ == null ? org.mojolang.mojo.lang.Document.getDefaultInstance() : document_;
      } else {
        return documentBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public Builder setDocument(org.mojolang.mojo.lang.Document value) {
      if (documentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        document_ = value;
        onChanged();
      } else {
        documentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public Builder setDocument(
        org.mojolang.mojo.lang.Document.Builder builderForValue) {
      if (documentBuilder_ == null) {
        document_ = builderForValue.build();
        onChanged();
      } else {
        documentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public Builder mergeDocument(org.mojolang.mojo.lang.Document value) {
      if (documentBuilder_ == null) {
        if (document_ != null) {
          document_ =
            org.mojolang.mojo.lang.Document.newBuilder(document_).mergeFrom(value).buildPartial();
        } else {
          document_ = value;
        }
        onChanged();
      } else {
        documentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public Builder clearDocument() {
      if (documentBuilder_ == null) {
        document_ = null;
        onChanged();
      } else {
        document_ = null;
        documentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public org.mojolang.mojo.lang.Document.Builder getDocumentBuilder() {
      
      onChanged();
      return getDocumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    public org.mojolang.mojo.lang.DocumentOrBuilder getDocumentOrBuilder() {
      if (documentBuilder_ != null) {
        return documentBuilder_.getMessageOrBuilder();
      } else {
        return document_ == null ?
            org.mojolang.mojo.lang.Document.getDefaultInstance() : document_;
      }
    }
    /**
     * <code>.mojo.lang.Document document = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Document, org.mojolang.mojo.lang.Document.Builder, org.mojolang.mojo.lang.DocumentOrBuilder> 
        getDocumentFieldBuilder() {
      if (documentBuilder_ == null) {
        documentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Document, org.mojolang.mojo.lang.Document.Builder, org.mojolang.mojo.lang.DocumentOrBuilder>(
                getDocument(),
                getParentForChildren(),
                isClean());
        document_ = null;
      }
      return documentBuilder_;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <code>string package_name = 7;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string package_name = 7;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string package_name = 7;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string package_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>string package_name = 7;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sourceFileName_ = "";
    /**
     * <code>string source_file_name = 8;</code>
     * @return The sourceFileName.
     */
    public java.lang.String getSourceFileName() {
      java.lang.Object ref = sourceFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_file_name = 8;</code>
     * @return The bytes for sourceFileName.
     */
    public com.google.protobuf.ByteString
        getSourceFileNameBytes() {
      java.lang.Object ref = sourceFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_file_name = 8;</code>
     * @param value The sourceFileName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sourceFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string source_file_name = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceFileName() {
      
      sourceFileName_ = getDefaultInstance().getSourceFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string source_file_name = 8;</code>
     * @param value The bytes for sourceFileName to set.
     * @return This builder for chaining.
     */
    public Builder setSourceFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sourceFileName_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.lang.Position keywordPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> keywordPositionBuilder_;
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     * @return Whether the keywordPosition field is set.
     */
    public boolean hasKeywordPosition() {
      return keywordPositionBuilder_ != null || keywordPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     * @return The keywordPosition.
     */
    public org.mojolang.mojo.lang.Position getKeywordPosition() {
      if (keywordPositionBuilder_ == null) {
        return keywordPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : keywordPosition_;
      } else {
        return keywordPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public Builder setKeywordPosition(org.mojolang.mojo.lang.Position value) {
      if (keywordPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        keywordPosition_ = value;
        onChanged();
      } else {
        keywordPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public Builder setKeywordPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (keywordPositionBuilder_ == null) {
        keywordPosition_ = builderForValue.build();
        onChanged();
      } else {
        keywordPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public Builder mergeKeywordPosition(org.mojolang.mojo.lang.Position value) {
      if (keywordPositionBuilder_ == null) {
        if (keywordPosition_ != null) {
          keywordPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(keywordPosition_).mergeFrom(value).buildPartial();
        } else {
          keywordPosition_ = value;
        }
        onChanged();
      } else {
        keywordPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public Builder clearKeywordPosition() {
      if (keywordPositionBuilder_ == null) {
        keywordPosition_ = null;
        onChanged();
      } else {
        keywordPosition_ = null;
        keywordPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getKeywordPositionBuilder() {
      
      onChanged();
      return getKeywordPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getKeywordPositionOrBuilder() {
      if (keywordPositionBuilder_ != null) {
        return keywordPositionBuilder_.getMessageOrBuilder();
      } else {
        return keywordPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : keywordPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position keyword_position = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getKeywordPositionFieldBuilder() {
      if (keywordPositionBuilder_ == null) {
        keywordPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getKeywordPosition(),
                getParentForChildren(),
                isClean());
        keywordPosition_ = null;
      }
      return keywordPositionBuilder_;
    }

    private java.lang.Object filter_ = "";
    /**
     * <code>string filter = 11;</code>
     * @return The filter.
     */
    public java.lang.String getFilter() {
      java.lang.Object ref = filter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filter = 11;</code>
     * @return The bytes for filter.
     */
    public com.google.protobuf.ByteString
        getFilterBytes() {
      java.lang.Object ref = filter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filter = 11;</code>
     * @param value The filter to set.
     * @return This builder for chaining.
     */
    public Builder setFilter(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filter = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilter() {
      
      filter_ = getDefaultInstance().getFilter();
      onChanged();
      return this;
    }
    /**
     * <code>string filter = 11;</code>
     * @param value The bytes for filter to set.
     * @return This builder for chaining.
     */
    public Builder setFilterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filter_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.lang.Attribute> attributes_ =
      java.util.Collections.emptyList();
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attributes_ = new java.util.ArrayList<org.mojolang.mojo.lang.Attribute>(attributes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Attribute, org.mojolang.mojo.lang.Attribute.Builder, org.mojolang.mojo.lang.AttributeOrBuilder> attributesBuilder_;

    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Attribute> getAttributesList() {
      if (attributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributes_);
      } else {
        return attributesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public int getAttributesCount() {
      if (attributesBuilder_ == null) {
        return attributes_.size();
      } else {
        return attributesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public org.mojolang.mojo.lang.Attribute getAttributes(int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);
      } else {
        return attributesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder setAttributes(
        int index, org.mojolang.mojo.lang.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.set(index, value);
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder setAttributes(
        int index, org.mojolang.mojo.lang.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder addAttributes(org.mojolang.mojo.lang.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder addAttributes(
        int index, org.mojolang.mojo.lang.Attribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(index, value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder addAttributes(
        org.mojolang.mojo.lang.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder addAttributes(
        int index, org.mojolang.mojo.lang.Attribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder addAllAttributes(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.Attribute> values) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributes_);
        onChanged();
      } else {
        attributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder clearAttributes() {
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public Builder removeAttributes(int index) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.remove(index);
        onChanged();
      } else {
        attributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public org.mojolang.mojo.lang.Attribute.Builder getAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public org.mojolang.mojo.lang.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);  } else {
        return attributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.AttributeOrBuilder> 
         getAttributesOrBuilderList() {
      if (attributesBuilder_ != null) {
        return attributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributes_);
      }
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public org.mojolang.mojo.lang.Attribute.Builder addAttributesBuilder() {
      return getAttributesFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.Attribute.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public org.mojolang.mojo.lang.Attribute.Builder addAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.Attribute.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.lang.Attribute attributes = 12;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Attribute.Builder> 
         getAttributesBuilderList() {
      return getAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Attribute, org.mojolang.mojo.lang.Attribute.Builder, org.mojolang.mojo.lang.AttributeOrBuilder> 
        getAttributesFieldBuilder() {
      if (attributesBuilder_ == null) {
        attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.Attribute, org.mojolang.mojo.lang.Attribute.Builder, org.mojolang.mojo.lang.AttributeOrBuilder>(
                attributes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        attributes_ = null;
      }
      return attributesBuilder_;
    }

    private java.lang.Object importPackageName_ = "";
    /**
     * <code>string import_package_name = 13;</code>
     * @return The importPackageName.
     */
    public java.lang.String getImportPackageName() {
      java.lang.Object ref = importPackageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importPackageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string import_package_name = 13;</code>
     * @return The bytes for importPackageName.
     */
    public com.google.protobuf.ByteString
        getImportPackageNameBytes() {
      java.lang.Object ref = importPackageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importPackageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string import_package_name = 13;</code>
     * @param value The importPackageName to set.
     * @return This builder for chaining.
     */
    public Builder setImportPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      importPackageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string import_package_name = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportPackageName() {
      
      importPackageName_ = getDefaultInstance().getImportPackageName();
      onChanged();
      return this;
    }
    /**
     * <code>string import_package_name = 13;</code>
     * @param value The bytes for importPackageName to set.
     * @return This builder for chaining.
     */
    public Builder setImportPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      importPackageName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object importPackageAlias_ = "";
    /**
     * <code>string import_package_alias = 14;</code>
     * @return The importPackageAlias.
     */
    public java.lang.String getImportPackageAlias() {
      java.lang.Object ref = importPackageAlias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importPackageAlias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string import_package_alias = 14;</code>
     * @return The bytes for importPackageAlias.
     */
    public com.google.protobuf.ByteString
        getImportPackageAliasBytes() {
      java.lang.Object ref = importPackageAlias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importPackageAlias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string import_package_alias = 14;</code>
     * @param value The importPackageAlias to set.
     * @return This builder for chaining.
     */
    public Builder setImportPackageAlias(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      importPackageAlias_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string import_package_alias = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportPackageAlias() {
      
      importPackageAlias_ = getDefaultInstance().getImportPackageAlias();
      onChanged();
      return this;
    }
    /**
     * <code>string import_package_alias = 14;</code>
     * @param value The bytes for importPackageAlias to set.
     * @return This builder for chaining.
     */
    public Builder setImportPackageAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      importPackageAlias_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object importFileName_ = "";
    /**
     * <code>string import_file_name = 15;</code>
     * @return The importFileName.
     */
    public java.lang.String getImportFileName() {
      java.lang.Object ref = importFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        importFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string import_file_name = 15;</code>
     * @return The bytes for importFileName.
     */
    public com.google.protobuf.ByteString
        getImportFileNameBytes() {
      java.lang.Object ref = importFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        importFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string import_file_name = 15;</code>
     * @param value The importFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImportFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      importFileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string import_file_name = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportFileName() {
      
      importFileName_ = getDefaultInstance().getImportFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string import_file_name = 15;</code>
     * @param value The bytes for importFileName to set.
     * @return This builder for chaining.
     */
    public Builder setImportFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      importFileName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.lang.Identifier> identifiers_ =
      java.util.Collections.emptyList();
    private void ensureIdentifiersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        identifiers_ = new java.util.ArrayList<org.mojolang.mojo.lang.Identifier>(identifiers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Identifier, org.mojolang.mojo.lang.Identifier.Builder, org.mojolang.mojo.lang.IdentifierOrBuilder> identifiersBuilder_;

    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Identifier> getIdentifiersList() {
      if (identifiersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(identifiers_);
      } else {
        return identifiersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public int getIdentifiersCount() {
      if (identifiersBuilder_ == null) {
        return identifiers_.size();
      } else {
        return identifiersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public org.mojolang.mojo.lang.Identifier getIdentifiers(int index) {
      if (identifiersBuilder_ == null) {
        return identifiers_.get(index);
      } else {
        return identifiersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder setIdentifiers(
        int index, org.mojolang.mojo.lang.Identifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.set(index, value);
        onChanged();
      } else {
        identifiersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder setIdentifiers(
        int index, org.mojolang.mojo.lang.Identifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.set(index, builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder addIdentifiers(org.mojolang.mojo.lang.Identifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.add(value);
        onChanged();
      } else {
        identifiersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder addIdentifiers(
        int index, org.mojolang.mojo.lang.Identifier value) {
      if (identifiersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdentifiersIsMutable();
        identifiers_.add(index, value);
        onChanged();
      } else {
        identifiersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder addIdentifiers(
        org.mojolang.mojo.lang.Identifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.add(builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder addIdentifiers(
        int index, org.mojolang.mojo.lang.Identifier.Builder builderForValue) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.add(index, builderForValue.build());
        onChanged();
      } else {
        identifiersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder addAllIdentifiers(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.Identifier> values) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, identifiers_);
        onChanged();
      } else {
        identifiersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder clearIdentifiers() {
      if (identifiersBuilder_ == null) {
        identifiers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        identifiersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public Builder removeIdentifiers(int index) {
      if (identifiersBuilder_ == null) {
        ensureIdentifiersIsMutable();
        identifiers_.remove(index);
        onChanged();
      } else {
        identifiersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public org.mojolang.mojo.lang.Identifier.Builder getIdentifiersBuilder(
        int index) {
      return getIdentifiersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public org.mojolang.mojo.lang.IdentifierOrBuilder getIdentifiersOrBuilder(
        int index) {
      if (identifiersBuilder_ == null) {
        return identifiers_.get(index);  } else {
        return identifiersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.IdentifierOrBuilder> 
         getIdentifiersOrBuilderList() {
      if (identifiersBuilder_ != null) {
        return identifiersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(identifiers_);
      }
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public org.mojolang.mojo.lang.Identifier.Builder addIdentifiersBuilder() {
      return getIdentifiersFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.Identifier.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public org.mojolang.mojo.lang.Identifier.Builder addIdentifiersBuilder(
        int index) {
      return getIdentifiersFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.Identifier.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.lang.Identifier identifiers = 16;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Identifier.Builder> 
         getIdentifiersBuilderList() {
      return getIdentifiersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Identifier, org.mojolang.mojo.lang.Identifier.Builder, org.mojolang.mojo.lang.IdentifierOrBuilder> 
        getIdentifiersFieldBuilder() {
      if (identifiersBuilder_ == null) {
        identifiersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.Identifier, org.mojolang.mojo.lang.Identifier.Builder, org.mojolang.mojo.lang.IdentifierOrBuilder>(
                identifiers_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        identifiers_ = null;
      }
      return identifiersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.lang.ImportDecl)
  }

  // @@protoc_insertion_point(class_scope:mojo.lang.ImportDecl)
  private static final org.mojolang.mojo.lang.ImportDecl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.lang.ImportDecl();
  }

  public static org.mojolang.mojo.lang.ImportDecl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImportDecl>
      PARSER = new com.google.protobuf.AbstractParser<ImportDecl>() {
    @java.lang.Override
    public ImportDecl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImportDecl(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImportDecl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImportDecl> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.lang.ImportDecl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

