// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/pattern.proto

package org.mojolang.mojo.lang;

public interface PatternOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.lang.Pattern)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
