// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/pattern.proto

package org.mojolang.mojo.lang;

public final class PatternProto {
  private PatternProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_lang_Pattern_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_lang_Pattern_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/lang/pattern.proto\022\tmojo.lang\"\030\n\007" +
      "Pattern\022\r\n\005value\030\001 \001(\tBY\n\026org.mojolang.m" +
      "ojo.langB\014PatternProtoP\001Z/github.com/moj" +
      "o-lang/lang/go/pkg/mojo/lang;langb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_lang_Pattern_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_lang_Pattern_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_lang_Pattern_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
