// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojo/lang/type.proto

package lang

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

///
type Type struct {
	// Types that are valid to be assigned to Type:
	//	*Type_EnumType
	//	*Type_StructType
	//	*Type_InterfaceType
	//	*Type_FuncType
	//	*Type_NominalType
	Type                 isType_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{0}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

type isType_Type interface {
	isType_Type()
}

type Type_EnumType struct {
	EnumType *EnumType `protobuf:"bytes,2,opt,name=enum_type,json=enumType,proto3,oneof"`
}

type Type_StructType struct {
	StructType *StructType `protobuf:"bytes,3,opt,name=struct_type,json=structType,proto3,oneof"`
}

type Type_InterfaceType struct {
	InterfaceType *InterfaceType `protobuf:"bytes,4,opt,name=interface_type,json=interfaceType,proto3,oneof"`
}

type Type_FuncType struct {
	FuncType *FuncType `protobuf:"bytes,5,opt,name=func_type,json=funcType,proto3,oneof"`
}

type Type_NominalType struct {
	NominalType *NominalType `protobuf:"bytes,6,opt,name=nominal_type,json=nominalType,proto3,oneof"`
}

func (*Type_EnumType) isType_Type() {}

func (*Type_StructType) isType_Type() {}

func (*Type_InterfaceType) isType_Type() {}

func (*Type_FuncType) isType_Type() {}

func (*Type_NominalType) isType_Type() {}

func (m *Type) GetType() isType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Type) GetEnumType() *EnumType {
	if x, ok := m.GetType().(*Type_EnumType); ok {
		return x.EnumType
	}
	return nil
}

func (m *Type) GetStructType() *StructType {
	if x, ok := m.GetType().(*Type_StructType); ok {
		return x.StructType
	}
	return nil
}

func (m *Type) GetInterfaceType() *InterfaceType {
	if x, ok := m.GetType().(*Type_InterfaceType); ok {
		return x.InterfaceType
	}
	return nil
}

func (m *Type) GetFuncType() *FuncType {
	if x, ok := m.GetType().(*Type_FuncType); ok {
		return x.FuncType
	}
	return nil
}

func (m *Type) GetNominalType() *NominalType {
	if x, ok := m.GetType().(*Type_NominalType); ok {
		return x.NominalType
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Type) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Type_OneofMarshaler, _Type_OneofUnmarshaler, _Type_OneofSizer, []interface{}{
		(*Type_EnumType)(nil),
		(*Type_StructType)(nil),
		(*Type_InterfaceType)(nil),
		(*Type_FuncType)(nil),
		(*Type_NominalType)(nil),
	}
}

func _Type_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Type)
	// type
	switch x := m.Type.(type) {
	case *Type_EnumType:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EnumType); err != nil {
			return err
		}
	case *Type_StructType:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StructType); err != nil {
			return err
		}
	case *Type_InterfaceType:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InterfaceType); err != nil {
			return err
		}
	case *Type_FuncType:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FuncType); err != nil {
			return err
		}
	case *Type_NominalType:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NominalType); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Type.Type has unexpected type %T", x)
	}
	return nil
}

func _Type_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Type)
	switch tag {
	case 2: // type.enum_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnumType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_EnumType{msg}
		return true, err
	case 3: // type.struct_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StructType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_StructType{msg}
		return true, err
	case 4: // type.interface_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InterfaceType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_InterfaceType{msg}
		return true, err
	case 5: // type.func_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FuncType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_FuncType{msg}
		return true, err
	case 6: // type.nominal_type
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NominalType)
		err := b.DecodeMessage(msg)
		m.Type = &Type_NominalType{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Type_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Type)
	// type
	switch x := m.Type.(type) {
	case *Type_EnumType:
		s := proto.Size(x.EnumType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_StructType:
		s := proto.Size(x.StructType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_InterfaceType:
		s := proto.Size(x.InterfaceType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_FuncType:
		s := proto.Size(x.FuncType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Type_NominalType:
		s := proto.Size(x.NominalType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EnumType struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	//
	Enumerators []*ValueDecl `protobuf:"bytes,10,rep,name=enumerators,proto3" json:"enumerators,omitempty"`
	//
	UnderlyingType       *NominalType `protobuf:"bytes,11,opt,name=underlying_type,json=underlyingType,proto3" json:"underlying_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnumType) Reset()         { *m = EnumType{} }
func (m *EnumType) String() string { return proto.CompactTextString(m) }
func (*EnumType) ProtoMessage()    {}
func (*EnumType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{1}
}

func (m *EnumType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumType.Unmarshal(m, b)
}
func (m *EnumType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumType.Marshal(b, m, deterministic)
}
func (m *EnumType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumType.Merge(m, src)
}
func (m *EnumType) XXX_Size() int {
	return xxx_messageInfo_EnumType.Size(m)
}
func (m *EnumType) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumType.DiscardUnknown(m)
}

var xxx_messageInfo_EnumType proto.InternalMessageInfo

func (m *EnumType) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *EnumType) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *EnumType) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *EnumType) GetEnumerators() []*ValueDecl {
	if m != nil {
		return m.Enumerators
	}
	return nil
}

func (m *EnumType) GetUnderlyingType() *NominalType {
	if m != nil {
		return m.UnderlyingType
	}
	return nil
}

type StructType struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	/// A Field represents a Field declaration list in a struct type,
	/// a method list in an interface type, or a parameter/result declaration
	/// in a signature.
	///
	Fields []*ValueDecl `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	///
	Inherits             []*NominalType `protobuf:"bytes,11,rep,name=inherits,proto3" json:"inherits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StructType) Reset()         { *m = StructType{} }
func (m *StructType) String() string { return proto.CompactTextString(m) }
func (*StructType) ProtoMessage()    {}
func (*StructType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{2}
}

func (m *StructType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructType.Unmarshal(m, b)
}
func (m *StructType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructType.Marshal(b, m, deterministic)
}
func (m *StructType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructType.Merge(m, src)
}
func (m *StructType) XXX_Size() int {
	return xxx_messageInfo_StructType.Size(m)
}
func (m *StructType) XXX_DiscardUnknown() {
	xxx_messageInfo_StructType.DiscardUnknown(m)
}

var xxx_messageInfo_StructType proto.InternalMessageInfo

func (m *StructType) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *StructType) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *StructType) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *StructType) GetFields() []*ValueDecl {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *StructType) GetInherits() []*NominalType {
	if m != nil {
		return m.Inherits
	}
	return nil
}

type InterfaceType struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Methods []*FuncDecl `protobuf:"bytes,10,rep,name=methods,proto3" json:"methods,omitempty"`
	///
	Inherits             []*NominalType `protobuf:"bytes,11,rep,name=inherits,proto3" json:"inherits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InterfaceType) Reset()         { *m = InterfaceType{} }
func (m *InterfaceType) String() string { return proto.CompactTextString(m) }
func (*InterfaceType) ProtoMessage()    {}
func (*InterfaceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{3}
}

func (m *InterfaceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceType.Unmarshal(m, b)
}
func (m *InterfaceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceType.Marshal(b, m, deterministic)
}
func (m *InterfaceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceType.Merge(m, src)
}
func (m *InterfaceType) XXX_Size() int {
	return xxx_messageInfo_InterfaceType.Size(m)
}
func (m *InterfaceType) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceType.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceType proto.InternalMessageInfo

func (m *InterfaceType) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *InterfaceType) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *InterfaceType) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *InterfaceType) GetMethods() []*FuncDecl {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *InterfaceType) GetInherits() []*NominalType {
	if m != nil {
		return m.Inherits
	}
	return nil
}

type FuncType struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Parameters []*ValueDecl `protobuf:"bytes,10,rep,name=parameters,proto3" json:"parameters,omitempty"`
	///
	ReturnType           *NominalType `protobuf:"bytes,11,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FuncType) Reset()         { *m = FuncType{} }
func (m *FuncType) String() string { return proto.CompactTextString(m) }
func (*FuncType) ProtoMessage()    {}
func (*FuncType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{4}
}

func (m *FuncType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncType.Unmarshal(m, b)
}
func (m *FuncType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncType.Marshal(b, m, deterministic)
}
func (m *FuncType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncType.Merge(m, src)
}
func (m *FuncType) XXX_Size() int {
	return xxx_messageInfo_FuncType.Size(m)
}
func (m *FuncType) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncType.DiscardUnknown(m)
}

var xxx_messageInfo_FuncType proto.InternalMessageInfo

func (m *FuncType) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *FuncType) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *FuncType) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *FuncType) GetParameters() []*ValueDecl {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *FuncType) GetReturnType() *NominalType {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

type NominalType struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	TypeDeclaration *TypeDeclaration `protobuf:"bytes,11,opt,name=type_declaration,json=typeDeclaration,proto3" json:"type_declaration,omitempty"`
	///
	GenericArguments []*GenericArgument `protobuf:"bytes,12,rep,name=generic_arguments,json=genericArguments,proto3" json:"generic_arguments,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	EnclosingType        *NominalType `protobuf:"bytes,14,opt,name=enclosing_type,json=enclosingType,proto3" json:"enclosing_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NominalType) Reset()         { *m = NominalType{} }
func (m *NominalType) String() string { return proto.CompactTextString(m) }
func (*NominalType) ProtoMessage()    {}
func (*NominalType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{5}
}

func (m *NominalType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NominalType.Unmarshal(m, b)
}
func (m *NominalType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NominalType.Marshal(b, m, deterministic)
}
func (m *NominalType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NominalType.Merge(m, src)
}
func (m *NominalType) XXX_Size() int {
	return xxx_messageInfo_NominalType.Size(m)
}
func (m *NominalType) XXX_DiscardUnknown() {
	xxx_messageInfo_NominalType.DiscardUnknown(m)
}

var xxx_messageInfo_NominalType proto.InternalMessageInfo

func (m *NominalType) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *NominalType) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *NominalType) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *NominalType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NominalType) GetTypeDeclaration() *TypeDeclaration {
	if m != nil {
		return m.TypeDeclaration
	}
	return nil
}

func (m *NominalType) GetGenericArguments() []*GenericArgument {
	if m != nil {
		return m.GenericArguments
	}
	return nil
}

func (m *NominalType) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *NominalType) GetEnclosingType() *NominalType {
	if m != nil {
		return m.EnclosingType
	}
	return nil
}

type TypeDeclaration struct {
	// Types that are valid to be assigned to TypeDeclaration:
	//	*TypeDeclaration_EnumDecl
	//	*TypeDeclaration_StructDecl
	//	*TypeDeclaration_InterfaceDecl
	//	*TypeDeclaration_NominalDecl
	//	*TypeDeclaration_TypeAliasDecl
	//	*TypeDeclaration_FuncDecl
	TypeDeclaration      isTypeDeclaration_TypeDeclaration `protobuf_oneof:"type_declaration"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *TypeDeclaration) Reset()         { *m = TypeDeclaration{} }
func (m *TypeDeclaration) String() string { return proto.CompactTextString(m) }
func (*TypeDeclaration) ProtoMessage()    {}
func (*TypeDeclaration) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{6}
}

func (m *TypeDeclaration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDeclaration.Unmarshal(m, b)
}
func (m *TypeDeclaration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDeclaration.Marshal(b, m, deterministic)
}
func (m *TypeDeclaration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDeclaration.Merge(m, src)
}
func (m *TypeDeclaration) XXX_Size() int {
	return xxx_messageInfo_TypeDeclaration.Size(m)
}
func (m *TypeDeclaration) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDeclaration.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDeclaration proto.InternalMessageInfo

type isTypeDeclaration_TypeDeclaration interface {
	isTypeDeclaration_TypeDeclaration()
}

type TypeDeclaration_EnumDecl struct {
	EnumDecl *EnumDecl `protobuf:"bytes,2,opt,name=enum_decl,json=enumDecl,proto3,oneof"`
}

type TypeDeclaration_StructDecl struct {
	StructDecl *StructDecl `protobuf:"bytes,3,opt,name=struct_decl,json=structDecl,proto3,oneof"`
}

type TypeDeclaration_InterfaceDecl struct {
	InterfaceDecl *InterfaceDecl `protobuf:"bytes,4,opt,name=interface_decl,json=interfaceDecl,proto3,oneof"`
}

type TypeDeclaration_NominalDecl struct {
	NominalDecl *NominalDecl `protobuf:"bytes,5,opt,name=nominal_decl,json=nominalDecl,proto3,oneof"`
}

type TypeDeclaration_TypeAliasDecl struct {
	TypeAliasDecl *TypeAliasDecl `protobuf:"bytes,6,opt,name=type_alias_decl,json=typeAliasDecl,proto3,oneof"`
}

type TypeDeclaration_FuncDecl struct {
	FuncDecl *FuncDecl `protobuf:"bytes,7,opt,name=func_decl,json=funcDecl,proto3,oneof"`
}

func (*TypeDeclaration_EnumDecl) isTypeDeclaration_TypeDeclaration() {}

func (*TypeDeclaration_StructDecl) isTypeDeclaration_TypeDeclaration() {}

func (*TypeDeclaration_InterfaceDecl) isTypeDeclaration_TypeDeclaration() {}

func (*TypeDeclaration_NominalDecl) isTypeDeclaration_TypeDeclaration() {}

func (*TypeDeclaration_TypeAliasDecl) isTypeDeclaration_TypeDeclaration() {}

func (*TypeDeclaration_FuncDecl) isTypeDeclaration_TypeDeclaration() {}

func (m *TypeDeclaration) GetTypeDeclaration() isTypeDeclaration_TypeDeclaration {
	if m != nil {
		return m.TypeDeclaration
	}
	return nil
}

func (m *TypeDeclaration) GetEnumDecl() *EnumDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_EnumDecl); ok {
		return x.EnumDecl
	}
	return nil
}

func (m *TypeDeclaration) GetStructDecl() *StructDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_StructDecl); ok {
		return x.StructDecl
	}
	return nil
}

func (m *TypeDeclaration) GetInterfaceDecl() *InterfaceDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_InterfaceDecl); ok {
		return x.InterfaceDecl
	}
	return nil
}

func (m *TypeDeclaration) GetNominalDecl() *NominalDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_NominalDecl); ok {
		return x.NominalDecl
	}
	return nil
}

func (m *TypeDeclaration) GetTypeAliasDecl() *TypeAliasDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_TypeAliasDecl); ok {
		return x.TypeAliasDecl
	}
	return nil
}

func (m *TypeDeclaration) GetFuncDecl() *FuncDecl {
	if x, ok := m.GetTypeDeclaration().(*TypeDeclaration_FuncDecl); ok {
		return x.FuncDecl
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TypeDeclaration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TypeDeclaration_OneofMarshaler, _TypeDeclaration_OneofUnmarshaler, _TypeDeclaration_OneofSizer, []interface{}{
		(*TypeDeclaration_EnumDecl)(nil),
		(*TypeDeclaration_StructDecl)(nil),
		(*TypeDeclaration_InterfaceDecl)(nil),
		(*TypeDeclaration_NominalDecl)(nil),
		(*TypeDeclaration_TypeAliasDecl)(nil),
		(*TypeDeclaration_FuncDecl)(nil),
	}
}

func _TypeDeclaration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TypeDeclaration)
	// type_declaration
	switch x := m.TypeDeclaration.(type) {
	case *TypeDeclaration_EnumDecl:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EnumDecl); err != nil {
			return err
		}
	case *TypeDeclaration_StructDecl:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StructDecl); err != nil {
			return err
		}
	case *TypeDeclaration_InterfaceDecl:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InterfaceDecl); err != nil {
			return err
		}
	case *TypeDeclaration_NominalDecl:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NominalDecl); err != nil {
			return err
		}
	case *TypeDeclaration_TypeAliasDecl:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TypeAliasDecl); err != nil {
			return err
		}
	case *TypeDeclaration_FuncDecl:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FuncDecl); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TypeDeclaration.TypeDeclaration has unexpected type %T", x)
	}
	return nil
}

func _TypeDeclaration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TypeDeclaration)
	switch tag {
	case 2: // type_declaration.enum_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnumDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_EnumDecl{msg}
		return true, err
	case 3: // type_declaration.struct_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StructDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_StructDecl{msg}
		return true, err
	case 4: // type_declaration.interface_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InterfaceDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_InterfaceDecl{msg}
		return true, err
	case 5: // type_declaration.nominal_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NominalDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_NominalDecl{msg}
		return true, err
	case 6: // type_declaration.type_alias_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TypeAliasDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_TypeAliasDecl{msg}
		return true, err
	case 7: // type_declaration.func_decl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FuncDecl)
		err := b.DecodeMessage(msg)
		m.TypeDeclaration = &TypeDeclaration_FuncDecl{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TypeDeclaration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TypeDeclaration)
	// type_declaration
	switch x := m.TypeDeclaration.(type) {
	case *TypeDeclaration_EnumDecl:
		s := proto.Size(x.EnumDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeDeclaration_StructDecl:
		s := proto.Size(x.StructDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeDeclaration_InterfaceDecl:
		s := proto.Size(x.InterfaceDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeDeclaration_NominalDecl:
		s := proto.Size(x.NominalDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeDeclaration_TypeAliasDecl:
		s := proto.Size(x.TypeAliasDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeDeclaration_FuncDecl:
		s := proto.Size(x.FuncDecl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

/// \brief This is the declaration of an enum.
///
/// For example:
///
/// \code
/// \endcode
///
/// The type of the decl itself is a MetatypeType; use getDeclaredType()
/// to get the declared type ("Bool" or "Optional" in the above example).
type EnumDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	EnclosingType *NominalType `protobuf:"bytes,13,opt,name=enclosing_type,json=enclosingType,proto3" json:"enclosing_type,omitempty"`
	//
	Type                 *EnumType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnumDecl) Reset()         { *m = EnumDecl{} }
func (m *EnumDecl) String() string { return proto.CompactTextString(m) }
func (*EnumDecl) ProtoMessage()    {}
func (*EnumDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{7}
}

func (m *EnumDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumDecl.Unmarshal(m, b)
}
func (m *EnumDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumDecl.Marshal(b, m, deterministic)
}
func (m *EnumDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumDecl.Merge(m, src)
}
func (m *EnumDecl) XXX_Size() int {
	return xxx_messageInfo_EnumDecl.Size(m)
}
func (m *EnumDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumDecl.DiscardUnknown(m)
}

var xxx_messageInfo_EnumDecl proto.InternalMessageInfo

func (m *EnumDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *EnumDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *EnumDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *EnumDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *EnumDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnumDecl) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *EnumDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *EnumDecl) GetEnclosingType() *NominalType {
	if m != nil {
		return m.EnclosingType
	}
	return nil
}

func (m *EnumDecl) GetType() *EnumType {
	if m != nil {
		return m.Type
	}
	return nil
}

type FuncDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Type *FuncType `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	///
	Attributes           []*Attribute `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FuncDecl) Reset()         { *m = FuncDecl{} }
func (m *FuncDecl) String() string { return proto.CompactTextString(m) }
func (*FuncDecl) ProtoMessage()    {}
func (*FuncDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{8}
}

func (m *FuncDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuncDecl.Unmarshal(m, b)
}
func (m *FuncDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuncDecl.Marshal(b, m, deterministic)
}
func (m *FuncDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuncDecl.Merge(m, src)
}
func (m *FuncDecl) XXX_Size() int {
	return xxx_messageInfo_FuncDecl.Size(m)
}
func (m *FuncDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_FuncDecl.DiscardUnknown(m)
}

var xxx_messageInfo_FuncDecl proto.InternalMessageInfo

func (m *FuncDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *FuncDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *FuncDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *FuncDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *FuncDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FuncDecl) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *FuncDecl) GetType() *FuncType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FuncDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type NominalDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	EnclosingType *NominalType `protobuf:"bytes,13,opt,name=enclosing_type,json=enclosingType,proto3" json:"enclosing_type,omitempty"`
	///
	Type                 *NominalType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NominalDecl) Reset()         { *m = NominalDecl{} }
func (m *NominalDecl) String() string { return proto.CompactTextString(m) }
func (*NominalDecl) ProtoMessage()    {}
func (*NominalDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{9}
}

func (m *NominalDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NominalDecl.Unmarshal(m, b)
}
func (m *NominalDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NominalDecl.Marshal(b, m, deterministic)
}
func (m *NominalDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NominalDecl.Merge(m, src)
}
func (m *NominalDecl) XXX_Size() int {
	return xxx_messageInfo_NominalDecl.Size(m)
}
func (m *NominalDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_NominalDecl.DiscardUnknown(m)
}

var xxx_messageInfo_NominalDecl proto.InternalMessageInfo

func (m *NominalDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *NominalDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *NominalDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *NominalDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *NominalDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NominalDecl) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *NominalDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *NominalDecl) GetEnclosingType() *NominalType {
	if m != nil {
		return m.EnclosingType
	}
	return nil
}

func (m *NominalDecl) GetType() *NominalType {
	if m != nil {
		return m.Type
	}
	return nil
}

/// `InterfaceDecl` - A declaration of an interface, for example:
///
/// ```mojo
///   interface Drawable {
///      draw()
///   }
/// ```
///
type InterfaceDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	Type *InterfaceType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	///
	NominalTypeDecls     []*NominalDecl `protobuf:"bytes,17,rep,name=nominal_type_decls,json=nominalTypeDecls,proto3" json:"nominal_type_decls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InterfaceDecl) Reset()         { *m = InterfaceDecl{} }
func (m *InterfaceDecl) String() string { return proto.CompactTextString(m) }
func (*InterfaceDecl) ProtoMessage()    {}
func (*InterfaceDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{10}
}

func (m *InterfaceDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceDecl.Unmarshal(m, b)
}
func (m *InterfaceDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceDecl.Marshal(b, m, deterministic)
}
func (m *InterfaceDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceDecl.Merge(m, src)
}
func (m *InterfaceDecl) XXX_Size() int {
	return xxx_messageInfo_InterfaceDecl.Size(m)
}
func (m *InterfaceDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceDecl.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceDecl proto.InternalMessageInfo

func (m *InterfaceDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *InterfaceDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *InterfaceDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *InterfaceDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *InterfaceDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterfaceDecl) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *InterfaceDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *InterfaceDecl) GetType() *InterfaceType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *InterfaceDecl) GetNominalTypeDecls() []*NominalDecl {
	if m != nil {
		return m.NominalTypeDecls
	}
	return nil
}

/// StructDecl - This is the declaration of a struct, for example:
///
/// ``` mojo
/// struct Complex { r : Double, i : Double }
/// ```
///
/// The type of the decl itself is a MetaType; use `Complex.type`
/// to get the `Complex`'s declared type.
///
type StructDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	EnclosingType *NominalType `protobuf:"bytes,13,opt,name=enclosing_type,json=enclosingType,proto3" json:"enclosing_type,omitempty"`
	///
	Type *StructType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	///
	NominalTypeDecls []*NominalDecl `protobuf:"bytes,17,rep,name=nominal_type_decls,json=nominalTypeDecls,proto3" json:"nominal_type_decls,omitempty"`
	///
	StructTypeDecls []*StructDecl `protobuf:"bytes,18,rep,name=struct_type_decls,json=structTypeDecls,proto3" json:"struct_type_decls,omitempty"`
	///
	EnumTypeDecls        []*EnumDecl `protobuf:"bytes,19,rep,name=enum_type_decls,json=enumTypeDecls,proto3" json:"enum_type_decls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StructDecl) Reset()         { *m = StructDecl{} }
func (m *StructDecl) String() string { return proto.CompactTextString(m) }
func (*StructDecl) ProtoMessage()    {}
func (*StructDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{11}
}

func (m *StructDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructDecl.Unmarshal(m, b)
}
func (m *StructDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructDecl.Marshal(b, m, deterministic)
}
func (m *StructDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructDecl.Merge(m, src)
}
func (m *StructDecl) XXX_Size() int {
	return xxx_messageInfo_StructDecl.Size(m)
}
func (m *StructDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_StructDecl.DiscardUnknown(m)
}

var xxx_messageInfo_StructDecl proto.InternalMessageInfo

func (m *StructDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *StructDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *StructDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *StructDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *StructDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StructDecl) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *StructDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *StructDecl) GetEnclosingType() *NominalType {
	if m != nil {
		return m.EnclosingType
	}
	return nil
}

func (m *StructDecl) GetType() *StructType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *StructDecl) GetNominalTypeDecls() []*NominalDecl {
	if m != nil {
		return m.NominalTypeDecls
	}
	return nil
}

func (m *StructDecl) GetStructTypeDecls() []*StructDecl {
	if m != nil {
		return m.StructTypeDecls
	}
	return nil
}

func (m *StructDecl) GetEnumTypeDecls() []*EnumDecl {
	if m != nil {
		return m.EnumTypeDecls
	}
	return nil
}

type TypeAliasDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeAliasDecl) Reset()         { *m = TypeAliasDecl{} }
func (m *TypeAliasDecl) String() string { return proto.CompactTextString(m) }
func (*TypeAliasDecl) ProtoMessage()    {}
func (*TypeAliasDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{12}
}

func (m *TypeAliasDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeAliasDecl.Unmarshal(m, b)
}
func (m *TypeAliasDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeAliasDecl.Marshal(b, m, deterministic)
}
func (m *TypeAliasDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeAliasDecl.Merge(m, src)
}
func (m *TypeAliasDecl) XXX_Size() int {
	return xxx_messageInfo_TypeAliasDecl.Size(m)
}
func (m *TypeAliasDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeAliasDecl.DiscardUnknown(m)
}

var xxx_messageInfo_TypeAliasDecl proto.InternalMessageInfo

func (m *TypeAliasDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *TypeAliasDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *TypeAliasDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *TypeAliasDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *TypeAliasDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

/// VarDecl - 'var' and 'const' declarations.
type ValueDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	Type *NominalType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	///
	DefaultValue         *Expression `protobuf:"bytes,13,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ValueDecl) Reset()         { *m = ValueDecl{} }
func (m *ValueDecl) String() string { return proto.CompactTextString(m) }
func (*ValueDecl) ProtoMessage()    {}
func (*ValueDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{13}
}

func (m *ValueDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueDecl.Unmarshal(m, b)
}
func (m *ValueDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueDecl.Marshal(b, m, deterministic)
}
func (m *ValueDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueDecl.Merge(m, src)
}
func (m *ValueDecl) XXX_Size() int {
	return xxx_messageInfo_ValueDecl.Size(m)
}
func (m *ValueDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueDecl.DiscardUnknown(m)
}

var xxx_messageInfo_ValueDecl proto.InternalMessageInfo

func (m *ValueDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *ValueDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *ValueDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *ValueDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *ValueDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValueDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ValueDecl) GetType() *NominalType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ValueDecl) GetDefaultValue() *Expression {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

///
type ConstDecl struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	Type *NominalType `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	///
	Value                *Expression `protobuf:"bytes,13,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConstDecl) Reset()         { *m = ConstDecl{} }
func (m *ConstDecl) String() string { return proto.CompactTextString(m) }
func (*ConstDecl) ProtoMessage()    {}
func (*ConstDecl) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{14}
}

func (m *ConstDecl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstDecl.Unmarshal(m, b)
}
func (m *ConstDecl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstDecl.Marshal(b, m, deterministic)
}
func (m *ConstDecl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstDecl.Merge(m, src)
}
func (m *ConstDecl) XXX_Size() int {
	return xxx_messageInfo_ConstDecl.Size(m)
}
func (m *ConstDecl) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstDecl.DiscardUnknown(m)
}

var xxx_messageInfo_ConstDecl proto.InternalMessageInfo

func (m *ConstDecl) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *ConstDecl) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *ConstDecl) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *ConstDecl) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *ConstDecl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConstDecl) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ConstDecl) GetType() *NominalType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ConstDecl) GetValue() *Expression {
	if m != nil {
		return m.Value
	}
	return nil
}

/// A type declaration that can have generic parameters attached to it.  Because
/// it has these generic parameters, it is always a DeclContext.
type GenericParameter struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	/// reserved field no. 3 for string document
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	GenericParameters []*GenericParameter `protobuf:"bytes,11,rep,name=generic_parameters,json=genericParameters,proto3" json:"generic_parameters,omitempty"`
	///
	Attributes []*Attribute `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty"`
	///
	Constraint           *NominalType `protobuf:"bytes,15,opt,name=constraint,proto3" json:"constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenericParameter) Reset()         { *m = GenericParameter{} }
func (m *GenericParameter) String() string { return proto.CompactTextString(m) }
func (*GenericParameter) ProtoMessage()    {}
func (*GenericParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{15}
}

func (m *GenericParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericParameter.Unmarshal(m, b)
}
func (m *GenericParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericParameter.Marshal(b, m, deterministic)
}
func (m *GenericParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericParameter.Merge(m, src)
}
func (m *GenericParameter) XXX_Size() int {
	return xxx_messageInfo_GenericParameter.Size(m)
}
func (m *GenericParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GenericParameter proto.InternalMessageInfo

func (m *GenericParameter) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *GenericParameter) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *GenericParameter) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *GenericParameter) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *GenericParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenericParameter) GetGenericParameters() []*GenericParameter {
	if m != nil {
		return m.GenericParameters
	}
	return nil
}

func (m *GenericParameter) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *GenericParameter) GetConstraint() *NominalType {
	if m != nil {
		return m.Constraint
	}
	return nil
}

type GenericArgument struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	///
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	///
	TypeDeclaration *TypeDeclaration `protobuf:"bytes,13,opt,name=type_declaration,json=typeDeclaration,proto3" json:"type_declaration,omitempty"`
	///
	GenericArguments []*GenericArgument `protobuf:"bytes,14,rep,name=generic_arguments,json=genericArguments,proto3" json:"generic_arguments,omitempty"`
	///
	Attributes           []*Attribute `protobuf:"bytes,15,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenericArgument) Reset()         { *m = GenericArgument{} }
func (m *GenericArgument) String() string { return proto.CompactTextString(m) }
func (*GenericArgument) ProtoMessage()    {}
func (*GenericArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{16}
}

func (m *GenericArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericArgument.Unmarshal(m, b)
}
func (m *GenericArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericArgument.Marshal(b, m, deterministic)
}
func (m *GenericArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericArgument.Merge(m, src)
}
func (m *GenericArgument) XXX_Size() int {
	return xxx_messageInfo_GenericArgument.Size(m)
}
func (m *GenericArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericArgument.DiscardUnknown(m)
}

var xxx_messageInfo_GenericArgument proto.InternalMessageInfo

func (m *GenericArgument) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *GenericArgument) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *GenericArgument) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *GenericArgument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenericArgument) GetTypeDeclaration() *TypeDeclaration {
	if m != nil {
		return m.TypeDeclaration
	}
	return nil
}

func (m *GenericArgument) GetGenericArguments() []*GenericArgument {
	if m != nil {
		return m.GenericArguments
	}
	return nil
}

func (m *GenericArgument) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

///
type Attribute struct {
	/// position of first character belonging to the Expr
	StartPosition *Position `protobuf:"bytes,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	/// position of first character immediately after the Expr
	EndPosition *Position `protobuf:"bytes,2,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	///
	Package string `protobuf:"bytes,6,opt,name=package,proto3" json:"package,omitempty"`
	/// the package which this attribute belong to
	Name                 string             `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	GenericArguments     []*GenericArgument `protobuf:"bytes,14,rep,name=generic_arguments,json=genericArguments,proto3" json:"generic_arguments,omitempty"`
	Expressions          []*Expression      `protobuf:"bytes,15,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e80737e12b1af1, []int{17}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetStartPosition() *Position {
	if m != nil {
		return m.StartPosition
	}
	return nil
}

func (m *Attribute) GetEndPosition() *Position {
	if m != nil {
		return m.EndPosition
	}
	return nil
}

func (m *Attribute) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetGenericArguments() []*GenericArgument {
	if m != nil {
		return m.GenericArguments
	}
	return nil
}

func (m *Attribute) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func init() {
	proto.RegisterType((*Type)(nil), "mojo.lang.Type")
	proto.RegisterType((*EnumType)(nil), "mojo.lang.EnumType")
	proto.RegisterType((*StructType)(nil), "mojo.lang.StructType")
	proto.RegisterType((*InterfaceType)(nil), "mojo.lang.InterfaceType")
	proto.RegisterType((*FuncType)(nil), "mojo.lang.FuncType")
	proto.RegisterType((*NominalType)(nil), "mojo.lang.NominalType")
	proto.RegisterType((*TypeDeclaration)(nil), "mojo.lang.TypeDeclaration")
	proto.RegisterType((*EnumDecl)(nil), "mojo.lang.EnumDecl")
	proto.RegisterType((*FuncDecl)(nil), "mojo.lang.FuncDecl")
	proto.RegisterType((*NominalDecl)(nil), "mojo.lang.NominalDecl")
	proto.RegisterType((*InterfaceDecl)(nil), "mojo.lang.InterfaceDecl")
	proto.RegisterType((*StructDecl)(nil), "mojo.lang.StructDecl")
	proto.RegisterType((*TypeAliasDecl)(nil), "mojo.lang.TypeAliasDecl")
	proto.RegisterType((*ValueDecl)(nil), "mojo.lang.ValueDecl")
	proto.RegisterType((*ConstDecl)(nil), "mojo.lang.ConstDecl")
	proto.RegisterType((*GenericParameter)(nil), "mojo.lang.GenericParameter")
	proto.RegisterType((*GenericArgument)(nil), "mojo.lang.GenericArgument")
	proto.RegisterType((*Attribute)(nil), "mojo.lang.Attribute")
}

func init() { proto.RegisterFile("mojo/lang/type.proto", fileDescriptor_a9e80737e12b1af1) }

var fileDescriptor_a9e80737e12b1af1 = []byte{
	// 1100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x4d, 0x8f, 0x1b, 0x35,
	0x18, 0x66, 0x27, 0xfb, 0x91, 0xbc, 0x93, 0x8f, 0x5d, 0xb7, 0x54, 0xa3, 0xe5, 0x52, 0xcd, 0x85,
	0x52, 0xda, 0x44, 0x5a, 0xd0, 0x16, 0x75, 0x85, 0x50, 0xc2, 0x2e, 0x05, 0x0e, 0x28, 0x0c, 0x88,
	0x03, 0x97, 0xc8, 0x3b, 0x71, 0xb2, 0x43, 0x27, 0x9e, 0xc8, 0xe3, 0x41, 0xec, 0x8d, 0x1b, 0x48,
	0x9c, 0xfa, 0x0b, 0xf8, 0x09, 0x70, 0xe0, 0x3f, 0x70, 0xe2, 0xce, 0x99, 0x3b, 0x3f, 0x00, 0xa9,
	0x07, 0xe4, 0xaf, 0x19, 0x67, 0xb3, 0xb3, 0x1f, 0x61, 0x2b, 0xd2, 0x2a, 0x97, 0x68, 0xc6, 0x7e,
	0x1e, 0x8f, 0xfd, 0xbc, 0x7e, 0xfd, 0xd8, 0x0e, 0xdc, 0x9e, 0x24, 0xdf, 0x24, 0x9d, 0x18, 0xd3,
	0x71, 0x87, 0x9f, 0x4e, 0x49, 0x7b, 0xca, 0x12, 0x9e, 0xa0, 0x9a, 0x28, 0x6d, 0x8b, 0xd2, 0x5d,
	0xaf, 0x00, 0x4c, 0x93, 0x34, 0xe2, 0x51, 0x42, 0x15, 0xc8, 0xae, 0x19, 0x26, 0x61, 0x36, 0x21,
	0x94, 0xeb, 0x9a, 0xdd, 0xa2, 0x86, 0x7c, 0x37, 0x65, 0x24, 0x4d, 0x73, 0x96, 0xff, 0xab, 0x03,
	0xeb, 0x5f, 0x9e, 0x4e, 0x09, 0xda, 0x83, 0x1a, 0xa1, 0xd9, 0x64, 0x20, 0x3e, 0xeb, 0x39, 0x77,
	0xd7, 0xee, 0xb9, 0x7b, 0xb7, 0xda, 0xf9, 0x77, 0xdb, 0x47, 0x34, 0x9b, 0x08, 0xdc, 0xc7, 0xaf,
	0x05, 0x55, 0xa2, 0x9f, 0xd1, 0x7b, 0xe0, 0xa6, 0x9c, 0x65, 0x21, 0x57, 0xac, 0x8a, 0x64, 0xbd,
	0x6e, 0xb1, 0xbe, 0x90, 0xb5, 0x9a, 0x07, 0x69, 0xfe, 0x86, 0xba, 0xd0, 0x8c, 0x28, 0x27, 0x6c,
	0x84, 0x43, 0xa2, 0xc8, 0xeb, 0x92, 0xec, 0x59, 0xe4, 0x4f, 0x0c, 0x40, 0xf3, 0x1b, 0x91, 0x5d,
	0x20, 0x3a, 0x3c, 0xca, 0x68, 0xa8, 0xd8, 0x1b, 0x73, 0x1d, 0xfe, 0x28, 0xa3, 0xa1, 0xe9, 0xf0,
	0x48, 0x3f, 0xa3, 0x03, 0xa8, 0xd3, 0x64, 0x12, 0x51, 0x1c, 0x2b, 0xda, 0xa6, 0xa4, 0xdd, 0xb1,
	0x68, 0x9f, 0xa9, 0x6a, 0xcd, 0x74, 0x69, 0xf1, 0xda, 0xdb, 0x84, 0x75, 0x41, 0xf2, 0x9f, 0x39,
	0x50, 0x35, 0x72, 0xa0, 0xc7, 0xd0, 0x4c, 0x39, 0x66, 0x7c, 0x60, 0xa2, 0xe1, 0xad, 0xcd, 0x75,
	0xa5, 0xaf, 0xab, 0x82, 0x86, 0x84, 0x9a, 0x57, 0xb4, 0x0f, 0x75, 0x42, 0x87, 0x05, 0xd3, 0x29,
	0x67, 0xba, 0x84, 0x0e, 0x73, 0x9e, 0x07, 0x5b, 0x53, 0x1c, 0x3e, 0xc5, 0x63, 0x35, 0x80, 0x5a,
	0x60, 0x5e, 0xd1, 0x3e, 0xb8, 0x22, 0x38, 0x84, 0x61, 0x9e, 0xb0, 0xd4, 0x83, 0xbb, 0x95, 0x7b,
	0xee, 0xde, 0x6d, 0xab, 0xc1, 0xaf, 0x70, 0x9c, 0x91, 0x43, 0x12, 0xc6, 0x81, 0x0d, 0x44, 0x1f,
	0x40, 0x2b, 0xa3, 0x43, 0xc2, 0xe2, 0xd3, 0x88, 0x8e, 0x95, 0x34, 0xee, 0x45, 0xd2, 0x04, 0xcd,
	0x02, 0x2e, 0xde, 0xfd, 0xe7, 0x6b, 0x00, 0x45, 0xb0, 0x97, 0x4c, 0x95, 0x07, 0xb0, 0x39, 0x8a,
	0x48, 0x3c, 0xbc, 0x58, 0x10, 0x8d, 0x41, 0x7b, 0x50, 0x8d, 0xe8, 0x09, 0x61, 0x11, 0x4f, 0x3d,
	0x57, 0xe2, 0xcb, 0x44, 0xc8, 0x71, 0xfe, 0xf7, 0x0e, 0x34, 0x66, 0xa6, 0xeb, 0x92, 0x29, 0xf0,
	0x10, 0xb6, 0x26, 0x84, 0x9f, 0x24, 0xb9, 0x04, 0x67, 0x33, 0x45, 0x2a, 0x60, 0x30, 0x0b, 0x49,
	0xf0, 0x83, 0x03, 0x55, 0x93, 0x73, 0x4b, 0x36, 0xfa, 0x77, 0x01, 0xa6, 0x98, 0xe1, 0x09, 0xe1,
	0xe4, 0x92, 0xa4, 0xb0, 0x70, 0xe8, 0x11, 0xb8, 0x8c, 0xf0, 0x8c, 0xd1, 0xab, 0xe4, 0x03, 0x28,
	0xa8, 0xcc, 0x85, 0xdf, 0x2a, 0xe0, 0x5a, 0x75, 0x4b, 0x26, 0x06, 0x82, 0x75, 0x8a, 0x27, 0xc4,
	0x03, 0x59, 0x2c, 0x9f, 0xd1, 0x11, 0x6c, 0x8b, 0x31, 0x0e, 0x86, 0x24, 0x8c, 0x31, 0xc3, 0xf2,
	0x4b, 0x6a, 0xbc, 0xbb, 0xd6, 0x97, 0xc4, 0x60, 0x0e, 0x0b, 0x44, 0xd0, 0xe2, 0xb3, 0x05, 0xe8,
	0x09, 0xec, 0x8c, 0x09, 0x25, 0x2c, 0x0a, 0x07, 0x98, 0x8d, 0xa5, 0x03, 0xa5, 0x5e, 0x5d, 0xca,
	0x6d, 0xb7, 0xf3, 0x44, 0x61, 0xba, 0x1a, 0x12, 0x6c, 0x8f, 0x67, 0x0b, 0x52, 0x11, 0x30, 0xcc,
	0x39, 0x8b, 0x8e, 0x33, 0x4e, 0x52, 0xaf, 0x31, 0x17, 0xb0, 0xae, 0xa9, 0x0c, 0x2c, 0x1c, 0x7a,
	0x1f, 0x9a, 0x84, 0x86, 0x71, 0x92, 0xe6, 0x6b, 0x58, 0xf3, 0xc2, 0x98, 0x35, 0x72, 0xb4, 0x0c,
	0xdb, 0x4f, 0x15, 0x68, 0x9d, 0x19, 0x62, 0x6e, 0x8a, 0x42, 0x98, 0x12, 0x53, 0x14, 0x70, 0x63,
	0x8a, 0xe2, 0xd9, 0x32, 0x45, 0xc9, 0x2a, 0x33, 0x45, 0xcd, 0xd3, 0xa6, 0x28, 0x99, 0x33, 0xa6,
	0x28, 0xc9, 0x17, 0x98, 0xa2, 0xe6, 0x17, 0xa6, 0x28, 0x9b, 0xb0, 0x0c, 0x4e, 0x36, 0xb0, 0x51,
	0xa6, 0x80, 0xa6, 0x1b, 0x83, 0x93, 0xe4, 0x1e, 0xc8, 0x90, 0x0e, 0x70, 0x1c, 0xe1, 0x54, 0xf1,
	0x37, 0xe7, 0x3a, 0x20, 0x24, 0xea, 0x0a, 0x80, 0xe9, 0x00, 0xb7, 0x0b, 0x72, 0x57, 0x96, 0xec,
	0xad, 0x73, 0x5d, 0xd9, 0x28, 0x36, 0xd2, 0xcf, 0x3d, 0x34, 0x3f, 0xfd, 0xfc, 0xdf, 0x2b, 0xca,
	0x64, 0x65, 0xa3, 0xff, 0x47, 0x06, 0x75, 0xa0, 0x6a, 0xb6, 0x51, 0x3a, 0x0c, 0x36, 0xe7, 0x50,
	0x57, 0x05, 0x39, 0xe8, 0x9a, 0x29, 0xf7, 0x29, 0x20, 0x93, 0x2b, 0xd6, 0xda, 0xa4, 0x16, 0xdb,
	0x37, 0xe6, 0x93, 0xa5, 0x6f, 0x30, 0x81, 0x49, 0xb1, 0x7e, 0xb1, 0x52, 0xcd, 0xa6, 0x4b, 0x7d,
	0xe1, 0x74, 0x69, 0x5c, 0x23, 0x5d, 0xd0, 0x9b, 0x6a, 0x37, 0xe4, 0xb5, 0x4a, 0xb7, 0x8a, 0x81,
	0xda, 0x2e, 0xfd, 0x58, 0x51, 0xc6, 0xb0, 0x8a, 0xe4, 0xe5, 0x91, 0x34, 0xa2, 0xd6, 0x4b, 0xb7,
	0xb3, 0x4a, 0xd4, 0xc5, 0x56, 0x48, 0xff, 0x8f, 0xc2, 0x99, 0x56, 0xd1, 0x58, 0xd2, 0xbc, 0xba,
	0x3f, 0x93, 0x57, 0x65, 0x24, 0x95, 0x5a, 0x7f, 0x56, 0xac, 0x6d, 0xe7, 0x2a, 0xa2, 0x2f, 0x2a,
	0xa2, 0x0f, 0x66, 0x42, 0x52, 0x7a, 0x44, 0xd5, 0xa9, 0x79, 0x08, 0xc8, 0x3e, 0x63, 0x4a, 0x57,
	0x4b, 0xbd, 0x9d, 0xb2, 0x6d, 0xb4, 0xdc, 0x77, 0x6e, 0x5b, 0xe7, 0x4c, 0x51, 0x90, 0xfa, 0xcf,
	0x36, 0xcc, 0x81, 0x6a, 0x15, 0xd7, 0x25, 0xcd, 0xd4, 0xb7, 0x66, 0xa6, 0xc5, 0xf9, 0xd7, 0x1e,
	0x37, 0x39, 0x27, 0x50, 0x17, 0x76, 0xac, 0xeb, 0x16, 0xdd, 0x08, 0x92, 0x8d, 0x9c, 0xbf, 0xbf,
	0x0c, 0x5a, 0xc5, 0x95, 0x8b, 0x6a, 0xe2, 0x00, 0x5a, 0xf9, 0x2d, 0x8f, 0x6e, 0xe0, 0xd6, 0xdc,
	0x81, 0xd0, 0xec, 0xbb, 0xc4, 0x80, 0x95, 0x95, 0xab, 0x39, 0xf9, 0xd7, 0x1a, 0x34, 0x66, 0xb6,
	0x7f, 0xaf, 0xe0, 0xb4, 0xf4, 0x9f, 0x3b, 0x50, 0xcb, 0x0f, 0x84, 0xaf, 0x62, 0xde, 0x2d, 0x96,
	0x2b, 0xd7, 0xb0, 0x25, 0xf4, 0x18, 0x1a, 0x43, 0x32, 0xc2, 0x59, 0xcc, 0x07, 0xdf, 0x0a, 0x25,
	0x75, 0x5a, 0xd9, 0x73, 0xf4, 0x28, 0xbf, 0x87, 0x0c, 0xea, 0x1a, 0x2b, 0x45, 0xf7, 0xff, 0x76,
	0xa0, 0xf6, 0x61, 0x42, 0x53, 0xbe, 0x92, 0x7f, 0x51, 0xf9, 0xdf, 0x86, 0x8d, 0x2b, 0xc8, 0xae,
	0x30, 0xfe, 0xcf, 0x15, 0xd8, 0x3e, 0xbb, 0xc2, 0xae, 0xdc, 0xe6, 0x45, 0xb8, 0xcd, 0x3e, 0x40,
	0x28, 0x26, 0x36, 0xc3, 0x11, 0xe5, 0x97, 0x04, 0xd2, 0x42, 0xfa, 0xff, 0x38, 0xd0, 0x3a, 0x73,
	0x65, 0xf2, 0x92, 0x5e, 0x29, 0x35, 0x6e, 0xe8, 0x4a, 0xa9, 0xf9, 0x9f, 0xaf, 0x94, 0x5a, 0x57,
	0x3c, 0x30, 0xfd, 0xe2, 0x40, 0x2d, 0xaf, 0x79, 0x09, 0x54, 0xbf, 0x31, 0xb9, 0x1e, 0x81, 0x5b,
	0xfc, 0x55, 0x64, 0xf4, 0x2a, 0x59, 0x49, 0x6c, 0x64, 0xef, 0x73, 0xb8, 0x93, 0xb0, 0xb1, 0x04,
	0x4a, 0x5c, 0xce, 0xe8, 0xd5, 0x44, 0xb0, 0xfb, 0x2c, 0xe1, 0x49, 0x7f, 0xed, 0xeb, 0xfb, 0xe3,
	0x88, 0x9f, 0x64, 0xc7, 0xed, 0x30, 0x99, 0x74, 0x04, 0xe4, 0xa1, 0xfc, 0x77, 0x4a, 0xfe, 0x8c,
	0x93, 0xce, 0xf4, 0xa9, 0x7a, 0x3e, 0x10, 0x3f, 0xc7, 0x9b, 0xf2, 0x9f, 0xaa, 0x77, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0x68, 0x71, 0x52, 0x1c, 0x1b, 0x00, 0x00,
}
