///
type Expr {
    /// position of first character belonging to the Expr
    start_pos: Position @1

    /// position of first character immediately after the Expr
    end_pos: Position @2

    ///
    kind: Int8 @3

    /// Whether the Expr represents something directly written in source or
    /// it was implicitly generated by the type-checker.
    implicit: Bool @4
}